### ISSUE TITLE
Do you have the homeworks for this course?

### ISSUE THREAD

**Issue by miladf2** [johnhhu2020/MITx-6.431x----Probability---The-Science-of-Uncertainty-and-Data#1]

**Comment by johnhhu2020** [comment]
Yes, I have.  I'm guessing you want to check if you understand the course properly through solving the homework.  While I think home work is not the only one can help you, try reading the book and put some time on it.

**Comment by johnhhu2020** [comment]
And good luck

**Comment by miladf2** [comment]
can you email or upload the homeworks?

**Comment by johnhhu2020** [comment]
The material just oversized too much, and I'm currently working on another
project.  And I think you can start the course when it starts, try to learn
something other than preparing something. (I'm guessing you want get fully
prepared to start the course, and I'm thinking the value is really the time
and effort you invested in the course, so please do not get fully prepared
for it)
